name: 'VectorLint'
description: 'Run VectorLint with reviewdog on pull requests'
author: 'TRocket Labs'

inputs:
  github_token:
    description: 'GitHub token for reviewdog'
    required: false
    default: ${{ github.token }}
  
  openai_api_key:
    description: 'OpenAI API key'
    required: false
  
  anthropic_api_key:
    description: 'Anthropic API key'
    required: false

  gemini_api_key:
    description: 'Google Gemini API key'
    required: false
  
  reporter:
    description: 'Reporter type (github-pr-check, github-pr-review, github-check)'
    required: false
    default: 'github-pr-check'
  
  filter_mode:
    description: 'Filter mode (added, diff_context, file, nofilter)'
    required: false
    default: 'added'
  
  fail_on_error:
    description: 'Fail if errors are found'
    required: false
    default: 'true'
  
  vectorlint_flags:
    description: 'Additional flags to pass to vectorlint'
    required: false
    default: ''
  
  working_directory:
    description: 'Working directory'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    
    - name: Run VectorLint with reviewdog
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
      run: |
        set -e
        
        # Check if API key is provided and set provider
        if [ -n "$OPENAI_API_KEY" ]; then
          export LLM_PROVIDER="openai"
        elif [ -n "$ANTHROPIC_API_KEY" ]; then
          export LLM_PROVIDER="anthropic"
        elif [ -n "$GEMINI_API_KEY" ]; then
          export LLM_PROVIDER="gemini"
        else
          echo "Error: An API key (OpenAI, Anthropic, or Gemini) must be provided"
          exit 1
        fi
        
        # Clone, build, and run vectorlint from branch
        git clone -b ft/reviewdog-test https://github.com/TRocket-Labs/vectorlint.git .vectorlint-temp
        cd .vectorlint-temp
        npm ci
        npm run build
        
        # Run using the built artifact from the repo root
        cd ..
        
        # Determine target files (only changed files for PRs)
        TARGET_FILES="."
        if [ -n "${{ github.base_ref }}" ]; then
          echo "Detected PR, calculating changed files against ${{ github.base_ref }}..."
          git fetch origin ${{ github.base_ref }} --depth=1
          # Find changed .md files
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep '\.md$' || true)
          
          if [ -z "$CHANGED" ]; then
            echo "No markdown files changed in this PR. Skipping analysis."
            echo '{"source": {"name": "vectorlint", "url": "https://github.com/TRocket-Labs/vectorlint"}, "diagnostics": []}' > vectorlint_result.json
            exit 0
          fi
          
          # Use changed files as targets
          TARGET_FILES=$(echo "$CHANGED" | tr '\n' ' ')
          echo "Scanning changed files: $TARGET_FILES"
        fi

        node .vectorlint-temp/dist/index.js --output rdjson --output-file vectorlint_result.json --prompts .vectorlint-temp/prompts ${{ inputs.vectorlint_flags }} $TARGET_FILES || true
        
        cat vectorlint_result.json | reviewdog -f=rdjson \
          -name="vectorlint" \
          -reporter=${{ inputs.reporter }} \
          -filter-mode=${{ inputs.filter_mode }} \
          -fail-on-error=${{ inputs.fail_on_error }}
          
        # Cleanup
        rm -rf .vectorlint-temp

branding:
  icon: 'check-circle'
  color: 'blue'
